### ISSUE TITLE
Difference between this and loopback-component-jsonapi?

### ISSUE THREAD

**Issue by byrondover** [digitalsadhu/loopback-jsonapi-model-serializer#2]
Please forgive the question: what's the difference between this `loopback-component-jsonapi`?

https://github.com/digitalsadhu/loopback-component-jsonapi

If I want to expose an API on top of my Loopback models which adheres to the JSON API spec, which should I use?

**Comment by digitalsadhu** [comment]
Hey, so the loopback-component-jsonapi module's goal is to provide everything you need to turn your loopback api into a jsonapi spec compliment api. It includes correct error formatting, serializing, deserializing and updating links between models. This module is only the serializer part and the goal is to replace the serializing in loopback-component-jsonapi with this project as it is a better implementation. (It handles some cases much better as I had learned a bunch from writing the component before writing this) 
At work, we use both at the moment. We use the component for the most part but for serializing custom remote methods and the like we use this project.

**Comment by byrondover** [comment]
Fabulous.

Thank you very much for the speedy answer, and for open-sourcing these projects!
